# Automated Scanning Detection – Log Analysis

## Overview
This analysis focuses on identifying automated reconnaissance and scanning activity using firewall, IDS, and application logs in a simulated enterprise environment.

The objective was to distinguish between normal user traffic and malicious automated behavior targeting sensitive endpoints.

---

## Normal Traffic Observed
- HTTPS traffic generated by common browsers such as Google Chrome, Mozilla Firefox, and curl.
- Benign request paths accessing standard application resources.
- Normal timing between requests indicating human interaction.

---

## Suspicious Patterns Identified
- User agents associated with scanning tools such as **Nmap** and **SQLMap**.
- Repeated requests targeting sensitive endpoints including:
  - `/admin/config`
  - `/wp-login.php`
  - `/upload`
  - `/?admin`
- Requests occurring at extremely short intervals, indicating automation.

---

## Source IP Analysis
- Multiple source IP addresses observed performing similar request patterns.
- Many IPs targeted administrative endpoints repeatedly.
- Time gaps between requests were less than a millisecond, strongly suggesting automated scanning activity.

---

## Detection and Security Controls
- Firewall, IDS, and application-level controls blocked most of the malicious requests.
- Alerts were triggered due to abnormal request frequency and suspicious user agents.
- No confirmed system compromise was detected.

---

## Analyst Conclusion
The observed activity is consistent with automated reconnaissance and scanning attempts targeting administrative interfaces. Existing security controls successfully prevented unauthorized access.

---

## Recommendations
- Continue monitoring for automated scanning activity.
- Improve alerting for repeated access attempts to sensitive endpoints.
- Correlate user-agent strings and request timing for early threat detection.
